export {
  LyricsPlayer,
  lyricsPlayer,
  usePlayerState,
  useCurrentLineIndex,
  usePlayerControls,
  type Lyrics,
  type LyricLine,
  type LyricWord,
  type PlayerState,
  type PlayerEvent,
  LoadLyrics,
  Play,
  Pause,
  Seek,
  Reset,
  Tick,
} from "./LyricsPlayer"
